FROM nginx:alpine
COPY devops/nginx.conf /etc/nginx/nginx.conf

RUN apk add --update nodejs
RUN apk add --update python
RUN apk add --update make
RUN apk add --update gcc
RUN apk add --update g++
RUN apk add --update git

RUN mkdir -p /opt/seal-static-site
WORKDIR /opt/seal-static-site
COPY . .

RUN npm install
RUN npm run build

EXPOSE 80
