FROM alpine:latest

RUN apk --no-cache add nginx nodejs tini nodejs-npm

COPY devops/nginx.conf /etc/nginx/nginx.conf
WORKDIR /opt/blog

COPY . .

EXPOSE 80

CMD ["/sbin/tini", "--", "/opt/blog/devops/run.sh"]
