on: [push]
name: docker
jobs:
  Docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_version:
          - 18.09
          # - 19.03
          # - 19.09
        docker_channel:
          - stable
          # - test
    steps:
      - uses: actions/checkout@master
      - name: setup docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: ${{ matrix.docker_version }}
          docker_channel: ${{ matrix.docker_channel }}

      - name: login docker hub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

      - name: build and publish fx d image
        if: always()
        run: |
          docker build -t metrue/blog:latest .
          docker push metrue/blog:latest"
